export type Test =
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string }
  | { a: number; b: string };
